language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
compiler: clang
before_script:
  - grunt
notifications:
  webhooks:
    urls:
      - "https://webhooks.gitter.im/e/93743e12f0a8e9b1a985"
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
